<template>
  <div>
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
    <iframe
      width="600"
      height="450"
      style="border:0"
      loading="lazy"
      allowfullscreen
      referrerpolicy="no-referrer-when-downgrade"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCFj8Vni52FfC9L1zpzxqH3ViUPmioa-Dw&q=Statue+of+Liberty"
    />
  </div>
</template>