<template>
  <div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
    <div>
      <YoutubeEmbed
        videoid="rT1MTP-Rrt8"
        playlabel="Play"
      />
    </div>
  </div>
</template>
