<template>
  <div>
    <div>
      <iframe
        id="ytplayer"
        type="text/html"
        width="640"
        height="360"
        src="https://www.youtube.com/embed/rT1MTP-Rrt8"
        frameborder="0"
      />
    </div>
  </div>
</template>
